name: returnwork

services:
  app:
    image: ${DOCKER_IMAGE}
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    deploy:
      resources:
        limits:
          memory: 400M
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-prod}
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/${DB_NAME:-returnWork}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME:-root}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD:-1234}
      - JWT_SECRET=${JWT_SECRET:-}
    networks:
      - app-network
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-1234}
      - MYSQL_DATABASE=${DB_NAME:-returnWork}
      - MYSQL_USER=${DB_USERNAME:-chusammin}
      - MYSQL_PASSWORD=${DB_PASSWORD:-1234}
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          memory: 400M
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
