spring:
  profiles:
    include: jwt, redis, email
    active: local

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        user_sql_comments: true
        default_batch_fetch_size: 500

